Update lab2.ipynb
Added a missing import at the bottom. also my version is getting an '
ValueError: Found array with dim 3. PCA expected <= 2.' at the reconstruct_image function so i can commit a version with everything ran